name: Python Tox on Fedora
description: Runs tests with Tox
inputs:
  tox_env:
    required: true
    default: 'py38'
    description: Tox environment to run the tests on
runs:
  using: docker
  image: docker://frenzymadness/fedora-python-tox
  entrypoint: tox
  args:
    - '-e${{ inputs.tox_env }}'
branding:
  color: green
  icon: check
